% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Assignment 3},
  pdfauthor={Rachel Montgomery},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Assignment 3}
\author{Rachel Montgomery}
\date{2023-09-18}

\begin{document}
\maketitle

\hypertarget{fpp3-8.8-exercises-5a-e}{%
\section{FPP3 8.8 Exercises: 5(a-e)}\label{fpp3-8.8-exercises-5a-e}}

\hypertarget{fit-and-forecast-methane-data-using-ets}{%
\subsection{Fit and Forecast Methane Data using
ETS}\label{fit-and-forecast-methane-data-using-ets}}

Data set \texttt{global\_economy} contains the annual Exports from many
countries. Select one country to analyze.

\hypertarget{a.-plot-the-exports-series-and-discuss-the-main-features-of-the-data.}{%
\subsubsection{a. Plot the Exports series and discuss the main features
of the
data.}\label{a.-plot-the-exports-series-and-discuss-the-main-features-of-the-data.}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# ?global\_economy}
\CommentTok{\# }
\CommentTok{\# view(global\_economy) \#\# commenting so knitted output isn\textquotesingle{}t as long }
\FunctionTok{glimpse}\NormalTok{(global\_economy)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Rows: 15,150
## Columns: 9
## Key: Country [263]
## $ Country    <fct> "Afghanistan", "Afghanistan", "Afghanistan", "Afghanistan",~
## $ Code       <fct> AFG, AFG, AFG, AFG, AFG, AFG, AFG, AFG, AFG, AFG, AFG, AFG,~
## $ Year       <dbl> 1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969,~
## $ GDP        <dbl> 537777811, 548888896, 546666678, 751111191, 800000044, 1006~
## $ Growth     <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,~
## $ CPI        <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,~
## $ Imports    <dbl> 7.024793, 8.097166, 9.349593, 16.863910, 18.055555, 21.4128~
## $ Exports    <dbl> 4.132233, 4.453443, 4.878051, 9.171601, 8.888893, 11.258279~
## $ Population <dbl> 8996351, 9166764, 9345868, 9533954, 9731361, 9938414, 10152~
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Filter for Exports for one country}
\NormalTok{global\_economy }\SpecialCharTok{\%\textgreater{}\%} 
    \FunctionTok{filter}\NormalTok{(Country }\SpecialCharTok{==} \StringTok{\textquotesingle{}Switzerland\textquotesingle{}}\NormalTok{) }\OtherTok{{-}\textgreater{}}\NormalTok{ switz\_econ  }
\DocumentationTok{\#\# I picked Switzerland b/c I traveled there last year (Geneva, Mt. Blanc) and absolutely loved it!}

\CommentTok{\# Convert to \textasciigrave{}tsibble\textasciigrave{}}
\NormalTok{switz\_econ }\OtherTok{\textless{}{-}} \FunctionTok{as\_tsibble}\NormalTok{(switz\_econ,}\AttributeTok{index=}\NormalTok{Year) }\CommentTok{\#making into tibble so can plots}

\CommentTok{\#subset further for training data {-} 2/3 of data is at 1998 so thats training, that onwards will be testing}
\NormalTok{switz\_econ }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{filter}\NormalTok{(Year }\SpecialCharTok{\textless{}=} \FunctionTok{year}\NormalTok{(}\FunctionTok{as.Date}\NormalTok{(}\StringTok{"1998{-}01{-}01"}\NormalTok{))) }\OtherTok{{-}\textgreater{}}\NormalTok{ switz\_train}

\NormalTok{switz\_train }\OtherTok{\textless{}{-}} \FunctionTok{as\_tsibble}\NormalTok{(switz\_train, }\AttributeTok{index=}\NormalTok{Year)}

\CommentTok{\#visualize the subset}
\NormalTok{switz\_econ }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{autoplot}\NormalTok{(Exports) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{y =} \StringTok{"Exports"}\NormalTok{, }\AttributeTok{title =} \StringTok{"Switzerland Exports"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{MontgomeryR_Assignment3_files/figure-latex/unnamed-chunk-2-1.pdf}

Overall, there is an upward trend of the data. There is missing data for
the 70s, which I'll attribute to missing data points.

There are several low points, which mostly can be explained by economic
recessions. - Switzerland's economy was marred by slow growth in the
1990s, having the weakest economic growth in Western Europe. The economy
was affected by a three-year recession from 1991 to 1993 - However,
beginning in 1997, a global resurgence in currency movement provided the
necessary stimulus to the Swiss economy. - There is a dip after 2000,
because of the worldwide stock market crashes in the wake of the 9/11
terrorist attacks, - The stock market collapse of 2007-2009 deeply
affected investment income earned abroad.

Overall, the economic history of Switzerland shows the long-term
transition from a poor rural economy to a world leader in finance with a
very high standard of living. By 1900 it had become one of the
wealthiest nations in Europe in terms of GDP.

\textbf{(All of this research is from Wikipedia.)}

\hypertarget{b.-use-an-etsann-model-to-forecast-the-series-and-plot-the-forecasts.}{%
\subsubsection{b. Use an ETS(A,N,N) model to forecast the series, and
plot the
forecasts.}\label{b.-use-an-etsann-model-to-forecast-the-series-and-plot-the-forecasts.}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#ETS (AAN) model }
\NormalTok{switz\_train}\SpecialCharTok{$}\NormalTok{Exports }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{ets}\NormalTok{(}\AttributeTok{model =} \StringTok{"AAN"}\NormalTok{)  }\SpecialCharTok{\%\textgreater{}\%} 
    \FunctionTok{forecast}\NormalTok{(}\AttributeTok{h =} \DecValTok{2}\NormalTok{) }\OtherTok{{-}\textgreater{}}\NormalTok{ switz\_holt}

\CommentTok{\#RMSE}
\FunctionTok{sqrt}\NormalTok{(}\FunctionTok{mean}\NormalTok{(switz\_holt}\SpecialCharTok{$}\NormalTok{residuals}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 2.530817
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#ETS(A,A,N) Holt model:}
\NormalTok{switz\_holt }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{autoplot}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\includegraphics{MontgomeryR_Assignment3_files/figure-latex/unnamed-chunk-4-1.pdf}

\hypertarget{c.-compute-the-rmse-values-for-the-training-data.}{%
\subsubsection{c.~Compute the RMSE values for the training
data.}\label{c.-compute-the-rmse-values-for-the-training-data.}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{switz\_train}\SpecialCharTok{$}\NormalTok{Exports }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{ets}\NormalTok{(}\AttributeTok{model =} \StringTok{"ANN"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} 
    \FunctionTok{forecast}\NormalTok{(}\AttributeTok{h =} \DecValTok{2}\NormalTok{) }\OtherTok{{-}\textgreater{}}\NormalTok{ switz\_ses}

\CommentTok{\#calculate corresponding RMSE}
\FunctionTok{sqrt}\NormalTok{(}\FunctionTok{mean}\NormalTok{(switz\_ses}\SpecialCharTok{$}\NormalTok{residuals}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 2.510073
\end{verbatim}

\hypertarget{d.-compare-the-results-to-those-from-an-etsaan-model.-remember-that-the-trended-model-is-using-one-more-parameter-than-the-simpler-model.-discuss-the-merits-of-the-two-forecasting-methods-for-this-data-set.}{%
\subsubsection{d.~Compare the results to those from an ETS(A,A,N) model.
(Remember that the trended model is using one more parameter than the
simpler model.) Discuss the merits of the two forecasting methods for
this data
set.}\label{d.-compare-the-results-to-those-from-an-etsaan-model.-remember-that-the-trended-model-is-using-one-more-parameter-than-the-simpler-model.-discuss-the-merits-of-the-two-forecasting-methods-for-this-data-set.}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Calculate RMSE for ETS(AAN) Model}
\NormalTok{rmse\_aan }\OtherTok{\textless{}{-}} \FunctionTok{sqrt}\NormalTok{(}\FunctionTok{mean}\NormalTok{(switz\_holt}\SpecialCharTok{$}\NormalTok{residuals}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{))}

\CommentTok{\# Calculate RMSE for ETS(ANN) Model}
\NormalTok{rmse\_ann }\OtherTok{\textless{}{-}} \FunctionTok{sqrt}\NormalTok{(}\FunctionTok{mean}\NormalTok{(switz\_ses}\SpecialCharTok{$}\NormalTok{residuals}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{))}

\CommentTok{\# Compare RMSE values}
\FunctionTok{cat}\NormalTok{(}\StringTok{"RMSE for ETS(AAN) Model:"}\NormalTok{, rmse\_aan, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
RMSE for ETS(AAN) Model: 2.530817 
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"RMSE for ETS(ANN) Model:"}\NormalTok{, rmse\_ann, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
RMSE for ETS(ANN) Model: 2.510073 
\end{verbatim}

Merits of ETS(AAN) Model (Trended Model):

\begin{itemize}
\item
  Useful for forecasting when there is evidence of a long-term growth or
  decline in the variable of interest.
\item
  It provides more flexibility in handling complex time series data with
  both seasonality and trend components.
\end{itemize}

Merits of ETS(ANN) Model (Non-Trended Model):

\begin{itemize}
\item
  Simplicity: This model is simpler with fewer parameters, which can
  make it easier to estimate and interpret.
\item
  Suitable for datasets that do not exhibit a clear, long-term trend or
  where the trend is not of primary interest.
\end{itemize}

For this dataset, I believe that the ETS(ANN) model (trended model) is a
better fit. This type of model can capture both the seasonality and the
underlying trend in the data, which can be valuable because this dataset
exhibits noticeable trend patterns over time.

\begin{quote}
Discuss which model has better fit and whether the more complex model is
necessary
\end{quote}

\hypertarget{e.-compare-the-forecasts-from-both-methods.-which-do-you-think-is-best}{%
\subsubsection{e. Compare the forecasts from both methods. Which do you
think is
best?}\label{e.-compare-the-forecasts-from-both-methods.-which-do-you-think-is-best}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# ETS(AAN) Model (Trended Model)}
\NormalTok{switz\_train }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{model}\NormalTok{(}\AttributeTok{ETS =} \FunctionTok{ETS}\NormalTok{(Exports }\SpecialCharTok{\textasciitilde{}} \FunctionTok{error}\NormalTok{(}\StringTok{"A"}\NormalTok{) }\SpecialCharTok{+} \FunctionTok{trend}\NormalTok{(}\StringTok{"A"}\NormalTok{) }\SpecialCharTok{+} \FunctionTok{season}\NormalTok{(}\StringTok{"N"}\NormalTok{))) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{forecast}\NormalTok{(}\AttributeTok{h =} \DecValTok{39}\NormalTok{) }\OtherTok{{-}\textgreater{}}\NormalTok{ switz\_holt}

\CommentTok{\# ETS(ANN) Model (Non{-}Trended Model)}
\NormalTok{switz\_train }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{model}\NormalTok{(}\AttributeTok{ETS =} \FunctionTok{ETS}\NormalTok{(Exports }\SpecialCharTok{\textasciitilde{}} \FunctionTok{error}\NormalTok{(}\StringTok{"A"}\NormalTok{) }\SpecialCharTok{+} \FunctionTok{season}\NormalTok{(}\StringTok{"N"}\NormalTok{))) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{forecast}\NormalTok{(}\AttributeTok{h =} \DecValTok{39}\NormalTok{) }\OtherTok{{-}\textgreater{}}\NormalTok{ switz\_ses}

\CommentTok{\# Plot the actual data and forecasts from both methods}

\NormalTok{switz\_train }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{autoplot}\NormalTok{(Exports) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{y =} \StringTok{"Exports"}\NormalTok{, }\AttributeTok{title =} \StringTok{"Comparison of Actual Data and Forecasts"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{autolayer}\NormalTok{(switz\_holt, }\AttributeTok{series =} \StringTok{"ETS(AAN) Forecast"}\NormalTok{, }\AttributeTok{PI =} \ConstantTok{FALSE}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{autolayer}\NormalTok{(switz\_ses, }\AttributeTok{series =} \StringTok{"ETS(ANN) Forecast"}\NormalTok{, }\AttributeTok{PI =} \ConstantTok{FALSE}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{scale\_color\_manual}\NormalTok{(}\AttributeTok{values =} \FunctionTok{c}\NormalTok{(}\StringTok{"blue"}\NormalTok{, }\StringTok{"red"}\NormalTok{, }\StringTok{"green"}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{legend.position =} \StringTok{"bottom"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{MontgomeryR_Assignment3_files/figure-latex/unnamed-chunk-7-1.pdf}

Because both forecasting models have similar RMSE values, it suggests
that both models are providing approximately equally accurate forecasts
for this dataset. I'll choose the ETS(ANN) model (trended model) because
it can better capture trends.

\hypertarget{fit-ets-so-it-finds-the-best-fitting-model-get-fit-statistics-the-fit}{%
\subsubsection{\texorpdfstring{Fit \texttt{ETS} so it finds the best
fitting model (get fit statistics the
fit)}{Fit ETS so it finds the best fitting model (get fit statistics the fit)}}\label{fit-ets-so-it-finds-the-best-fitting-model-get-fit-statistics-the-fit}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Fit ETS models and select the best one}
\NormalTok{best\_ets\_model }\OtherTok{\textless{}{-}} \FunctionTok{ets}\NormalTok{(switz\_train}\SpecialCharTok{$}\NormalTok{Exports, }\AttributeTok{ic =} \StringTok{"bic"}\NormalTok{)}

\CommentTok{\# Print the best{-}fitting ETS model}
\FunctionTok{summary}\NormalTok{(best\_ets\_model)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
ETS(M,N,N) 

Call:
 ets(y = switz_train$Exports, ic = "bic") 

  Smoothing parameters:
    alpha = 0.9999 

  Initial states:
    l = 47.0596 

  sigma:  0.0595

     AIC     AICc      BIC 
96.52882 98.12882 99.36214 

Training set error measures:
                      ME     RMSE      MAE        MPE     MAPE      MASE
Training set -0.01883127 2.510635 1.928044 -0.1948215 4.306336 0.9510363
                    ACF1
Training set 0.008134945
\end{verbatim}

\hypertarget{use-the-best-fitting-model-to-forecast-10-time-points-out}{%
\subsubsection{Use the best fitting model to forecast 10 time points
out}\label{use-the-best-fitting-model-to-forecast-10-time-points-out}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Forecast 10 time points ahead using the best{-}fitting ETS model}
\NormalTok{forecast\_horizon }\OtherTok{\textless{}{-}} \DecValTok{10}
\NormalTok{forecasts }\OtherTok{\textless{}{-}} \FunctionTok{forecast}\NormalTok{(best\_ets\_model, }\AttributeTok{h =}\NormalTok{ forecast\_horizon)}

\CommentTok{\# Print the forecasts}
\FunctionTok{print}\NormalTok{(forecasts)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    Point Forecast    Lo 80    Hi 80    Lo 95    Hi 95
## 40       46.70186 43.13817 50.26555 41.25166 52.15206
## 41       46.70186 41.65783 51.74590 38.98767 54.41605
## 42       46.70186 40.51883 52.88489 37.24573 56.15799
## 43       46.70186 39.55604 53.84768 35.77327 57.63045
## 44       46.70186 38.70554 54.69818 34.47255 58.93117
## 45       46.70186 37.93459 55.46914 33.29347 60.11025
## 46       46.70186 37.22373 56.17999 32.20631 61.19741
## 47       46.70186 36.56033 56.84340 31.19172 62.21200
## 48       46.70186 35.93559 57.46814 30.23626 63.16746
## 49       46.70186 35.34312 58.06060 29.33017 64.07355
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Plot the forecasts}
\FunctionTok{autoplot}\NormalTok{(forecasts) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{y =} \StringTok{"Exports"}\NormalTok{, }\AttributeTok{title =} \StringTok{"ETS Model Forecast"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{MontgomeryR_Assignment3_files/figure-latex/unnamed-chunk-10-1.pdf}

\hypertarget{report-the-model-and-interpret-each-smoothing-parameter}{%
\subsubsection{\texorpdfstring{\texttt{report} the model and interpret
each smoothing
parameter}{report the model and interpret each smoothing parameter}}\label{report-the-model-and-interpret-each-smoothing-parameter}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Print the best{-}fitting ETS model}
\FunctionTok{summary}\NormalTok{(best\_ets\_model)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## ETS(M,N,N) 
## 
## Call:
##  ets(y = switz_train$Exports, ic = "bic") 
## 
##   Smoothing parameters:
##     alpha = 0.9999 
## 
##   Initial states:
##     l = 47.0596 
## 
##   sigma:  0.0595
## 
##      AIC     AICc      BIC 
## 96.52882 98.12882 99.36214 
## 
## Training set error measures:
##                       ME     RMSE      MAE        MPE     MAPE      MASE
## Training set -0.01883127 2.510635 1.928044 -0.1948215 4.306336 0.9510363
##                     ACF1
## Training set 0.008134945
\end{verbatim}

\begin{quote}
Interpret the parameters
\end{quote}

\begin{itemize}
\item
  Alpha (α): 0.9999

  \begin{itemize}
  \tightlist
  \item
    Alpha is very close to 1, which indicates that the model assigns
    nearly all the weight to the most recent observation when making
    predictions. This means that the model relies heavily on the most
    recent data point and has little memory of past observations. It
    suggests very strong exponential smoothing in the model. Initial
    States:
  \end{itemize}
\item
  Initial Level (l): 47.0596

  \begin{itemize}
  \tightlist
  \item
    The initial level represents the estimated starting point for the
    series. In this case, it's approximately 47.0596, indicating that
    the model's initial estimate for the level of the time series is
    around this value. Sigma (σ):
  \end{itemize}
\item
  Sigma (σ): 0.0595

  \begin{itemize}
  \tightlist
  \item
    Sigma represents the estimated standard deviation of the error term
    in the model. A smaller sigma value suggests that the model's
    predictions are expected to be close to the actual values. In this
    case, a value of 0.0595 indicates that the model expects relatively
    low variability in the errors.
  \end{itemize}
\end{itemize}

Overall, the ETS(M,N,N) model with the given smoothing parameters
suggests that it places very high emphasis on the most recent data point
when making predictions (high alpha), does not incorporate a trend
component (N for ``None''), and does not incorporate a seasonal
component (N for ``None'').

\hypertarget{fit-and-forecast-methane-data-using-ets-1}{%
\subsection{Fit and Forecast Methane Data using
ETS}\label{fit-and-forecast-methane-data-using-ets-1}}

Use the globally averaged marine surface methane data from NOAA. Here's
the website where the data can be found:
\url{https://gml.noaa.gov/ccgg/}

\hypertarget{prepare-data}{%
\subsubsection{Prepare Data}\label{prepare-data}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{methane }\OtherTok{\textless{}{-}} \FunctionTok{read\_csv}\NormalTok{(}\StringTok{"methane\_data\_real.csv"}\NormalTok{)}

\DocumentationTok{\#\# make date the year and month }
\NormalTok{methane }\OtherTok{\textless{}{-}}\NormalTok{ methane }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{Date =} \FunctionTok{yearmonth}\NormalTok{(}\FunctionTok{paste}\NormalTok{(year, month, }\AttributeTok{sep =} \StringTok{"{-}"}\NormalTok{)))}
\end{Highlighting}
\end{Shaded}

note: CH4 expressed as a mole fraction in dry air, nanomol/mol,
abbreviated as ppb

\hypertarget{set-prediction-and-actual-data}{%
\subsubsection{Set Prediction and Actual
Data}\label{set-prediction-and-actual-data}}

\begin{itemize}
\item
  Create an object called \texttt{prediction\_methane} with the dates
  from July 1983-July 2017
\item
  Create a separate object called \texttt{actual\_methane} with the
  dates from August 2017-April 2022
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Filter for prediction\_methane (July 1983 to July 2017)}
\NormalTok{prediction\_methane }\OtherTok{\textless{}{-}}\NormalTok{ methane }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(Date }\SpecialCharTok{\textgreater{}=} \FunctionTok{yearmonth}\NormalTok{(}\StringTok{"1983{-}07"}\NormalTok{) }\SpecialCharTok{\&}\NormalTok{ Date }\SpecialCharTok{\textless{}=} \FunctionTok{yearmonth}\NormalTok{(}\StringTok{"2017{-}07"}\NormalTok{))}

\CommentTok{\# Filter for actual\_methane (August 2017 to April 2022)}
\NormalTok{actual\_methane }\OtherTok{\textless{}{-}}\NormalTok{ methane }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(Date }\SpecialCharTok{\textgreater{}=} \FunctionTok{yearmonth}\NormalTok{(}\StringTok{"2017{-}08"}\NormalTok{) }\SpecialCharTok{\&}\NormalTok{ Date }\SpecialCharTok{\textless{}=} \FunctionTok{yearmonth}\NormalTok{(}\StringTok{"2022{-}04"}\NormalTok{))}

\CommentTok{\# Convert to tsibble so we can use it in this notebook}
\NormalTok{prediction\_methane }\OtherTok{\textless{}{-}} \FunctionTok{as\_tsibble}\NormalTok{(prediction\_methane, }\AttributeTok{index =}\NormalTok{ Date)}
\NormalTok{actual\_methane }\OtherTok{\textless{}{-}} \FunctionTok{as\_tsibble}\NormalTok{(actual\_methane, }\AttributeTok{index =}\NormalTok{ Date)}

\CommentTok{\# Print the first few rows of prediction\_methane and actual\_methane}
\FunctionTok{print}\NormalTok{(}\StringTok{"prediction\_methane:"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] "prediction_methane:"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{head}\NormalTok{(prediction\_methane)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
# A tsibble: 6 x 8 [1M]
   year month decimal average average_unc trend trend_unc     Date
  <dbl> <dbl>   <dbl>   <dbl>       <dbl> <dbl>     <dbl>    <mth>
1  1983     7   1984.   1626.         2.1 1636.       1.4 1983 Jul
2  1983     8   1984.   1628          2.7 1636.       1.3 1983 Aug
3  1983     9   1984.   1638.         2.3 1637.       1.3 1983 Sep
4  1983    10   1984.   1645.         1.6 1637.       1.2 1983 Oct
5  1983    11   1984.   1643.         0.8 1638.       1.1 1983 Nov
6  1983    12   1984.   1640.         1   1638.       1   1983 Dec
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(}\StringTok{"actual\_methane:"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] "actual_methane:"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{head}\NormalTok{(actual\_methane)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
# A tsibble: 6 x 8 [1M]
   year month decimal average average_unc trend trend_unc     Date
  <dbl> <dbl>   <dbl>   <dbl>       <dbl> <dbl>     <dbl>    <mth>
1  2017     8   2018.   1845.         1.2 1850.       0.6 2017 Aug
2  2017     9   2018.   1853.         1   1851.       0.6 2017 Sep
3  2017    10   2018.   1858.         1   1852.       0.6 2017 Oct
4  2017    11   2018.   1859.         0.8 1852.       0.7 2017 Nov
5  2017    12   2018.   1857.         0.9 1853.       0.7 2017 Dec
6  2018     1   2018.   1854.         1   1854.       0.7 2018 Jan
\end{verbatim}

\hypertarget{plot-the-time-series-for-prediction_methane}{%
\subsubsection{\texorpdfstring{Plot the Time Series for
\texttt{prediction\_methane}}{Plot the Time Series for prediction\_methane}}\label{plot-the-time-series-for-prediction_methane}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Create a time series plot for prediction\_methane}

\NormalTok{prediction\_methane }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{autoplot}\NormalTok{(average) }\SpecialCharTok{+}
  \FunctionTok{ggtitle}\NormalTok{(}\StringTok{"Average Methane Prediction"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{xlab}\NormalTok{(}\StringTok{"Date"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{ylab}\NormalTok{(}\StringTok{"Average Methane Value"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{MontgomeryR_Assignment3_files/figure-latex/unnamed-chunk-14-1.pdf}

\hypertarget{fit-best-ets-model-and-report-fit-for-prediction_methane}{%
\subsubsection{\texorpdfstring{Fit Best ETS Model and Report Fit for
\texttt{prediction\_methane}}{Fit Best ETS Model and Report Fit for prediction\_methane}}\label{fit-best-ets-model-and-report-fit-for-prediction_methane}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Fit an ETS model}
\NormalTok{ets\_model }\OtherTok{\textless{}{-}}\NormalTok{ prediction\_methane }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{model}\NormalTok{(}\AttributeTok{ets =} \FunctionTok{ETS}\NormalTok{(average)) }\DocumentationTok{\#\# note to self: \textquotesingle{}ETS\textquotesingle{} has to be capital for the parameters}

\CommentTok{\# Report the fit}
\FunctionTok{report}\NormalTok{(ets\_model)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Series: average 
## Model: ETS(A,A,A) 
##   Smoothing parameters:
##     alpha = 0.9998977 
##     beta  = 0.03998295 
##     gamma = 0.000100864 
## 
##   Initial states:
##      l[0]     b[0]      s[0]      s[-1]    s[-2]  s[-3]    s[-4]    s[-5]
##  1632.071 1.083894 -5.195723 -0.6991533 1.428202 1.5365 1.412206 2.174231
##     s[-6]    s[-7]    s[-8]     s[-9]    s[-10]    s[-11]
##  3.996608 5.300397 4.670121 0.2858654 -6.189648 -8.719607
## 
##   sigma^2:  1.3754
## 
##      AIC     AICc      BIC 
## 2607.659 2609.224 2675.892
\end{verbatim}

\hypertarget{comment-on-the-smoothing-parameters-for-the-model}{%
\paragraph{Comment on the smoothing parameters for the
model}\label{comment-on-the-smoothing-parameters-for-the-model}}

\begin{itemize}
\item
  Alpha (α): 0.9998977

  \begin{itemize}
  \tightlist
  \item
    Alpha is the smoothing parameter for the error (innovation)
    component. Alpha is very close to 1, indicating that the model
    heavily relies on the most recent observations to forecast future
    values.
  \end{itemize}
\item
  Beta (β): 0.03998295

  \begin{itemize}
  \tightlist
  \item
    Beta is the smoothing parameter for the trend component. The
    relatively small beta value indicates that the trend component is
    evolving slowly over time.
  \end{itemize}
\item
  Gamma (γ): 0.000100864

  \begin{itemize}
  \tightlist
  \item
    Gamma is the smoothing parameter for the seasonal component. The low
    gamma value means that the model assigns less weight to the seasonal
    component, indicating that the seasonality is not changing rapidly
    over time.
  \end{itemize}
\end{itemize}

\hypertarget{discuss-what-the-magnitude-of-these-parameters-mean-include-the-type-of-model}{%
\paragraph{Discuss what the magnitude of these parameters mean (include
the type of
model)}\label{discuss-what-the-magnitude-of-these-parameters-mean-include-the-type-of-model}}

The ETS(A,A,A) model is characterized by high reactivity to recent
observations (high alpha), relatively slow trend evolution (low beta),
and relatively stable and consistent seasonality (low gamma).

\hypertarget{using-the-best-fitting-model-make-and-plot-a-forecast-to-april-2022-using-prediction_methane}{%
\subsubsection{\texorpdfstring{Using the best fitting model, make and
plot a forecast to April 2022 using
\texttt{prediction\_methane}}{Using the best fitting model, make and plot a forecast to April 2022 using prediction\_methane}}\label{using-the-best-fitting-model-make-and-plot-a-forecast-to-april-2022-using-prediction_methane}}

\hypertarget{plot-the-line-for-actual_methane-the-forecast-using-the-color-d55e00}{%
\paragraph{\texorpdfstring{Plot the line for \texttt{actual\_methane}
\textbf{over} the forecast using the color
\texttt{"\#D55E00"}}{Plot the line for actual\_methane  the forecast using the color "\#D55E00"}}\label{plot-the-line-for-actual_methane-the-forecast-using-the-color-d55e00}}

\begin{Shaded}
\begin{Highlighting}[]
\DocumentationTok{\#\# with the ets model, it automatically predicts the next value, which is the month of april}
\NormalTok{april\_forecast }\OtherTok{=}\NormalTok{ ets\_model }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{forecast}\NormalTok{(}\AttributeTok{h=}\FunctionTok{nrow}\NormalTok{(actual\_methane))}

\DocumentationTok{\#\#plot}

\FunctionTok{ggplot}\NormalTok{(prediction\_methane) }\SpecialCharTok{+}
  \FunctionTok{geom\_line}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{Date,}\AttributeTok{y=}\NormalTok{average, }\AttributeTok{color=}\StringTok{\textquotesingle{}Training\textquotesingle{}}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{geom\_line}\NormalTok{(}\AttributeTok{data=}\NormalTok{actual\_methane, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{Date, }\AttributeTok{y=}\NormalTok{average, }\AttributeTok{color=} \StringTok{\textquotesingle{}Actual\textquotesingle{}}\NormalTok{) ) }\SpecialCharTok{+}
  \FunctionTok{geom\_line}\NormalTok{(}\AttributeTok{data=}\NormalTok{april\_forecast, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{Date, }\AttributeTok{y=}\NormalTok{.mean, }\AttributeTok{color=}\StringTok{"Prediction"}\NormalTok{) ) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{ ( }\AttributeTok{title=} \StringTok{"Methane levels over time"}\NormalTok{,}
         \AttributeTok{x =} \StringTok{"Date"}\NormalTok{,}
         \AttributeTok{y =} \StringTok{"Average Methane Level"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{scale\_color\_manual}\NormalTok{( }\AttributeTok{name =} \StringTok{"Data Type"}\NormalTok{, }
                      \AttributeTok{values =} \FunctionTok{c}\NormalTok{(}\StringTok{"Training"} \OtherTok{=} \StringTok{"pink"}\NormalTok{, }\StringTok{"Actual"} \OtherTok{=} \StringTok{"\#D55E00"}\NormalTok{,}
                                                     \StringTok{"Prediction"} \OtherTok{=} \StringTok{"purple"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{MontgomeryR_Assignment3_files/figure-latex/unnamed-chunk-16-1.pdf}

\hypertarget{compute-point-accuracy-measures-between-the-forecasted-and-actual-values}{%
\subsubsection{Compute point accuracy measures between the forecasted
and actual
values}\label{compute-point-accuracy-measures-between-the-forecasted-and-actual-values}}

\hypertarget{discuss-whether-the-forecast-was-accurate-and-whether-there-was-any-bias-in-the-forecast}{%
\paragraph{Discuss whether the forecast was accurate and whether there
was any bias in the
forecast}\label{discuss-whether-the-forecast-was-accurate-and-whether-there-was-any-bias-in-the-forecast}}

The accuracy measures provide valuable insights into the performance of
your forecasted values compared to the actual values.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{april\_forecast }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{accuracy}\NormalTok{( }\AttributeTok{data=}\NormalTok{actual\_methane) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{select}\NormalTok{(RMSE, MAE, ME)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 1 x 3
##    RMSE   MAE    ME
##   <dbl> <dbl> <dbl>
## 1  11.2  7.97  7.95
\end{verbatim}

\begin{itemize}
\item
  Root Mean Squared Error (RMSE)**: 11.16

  \begin{itemize}
  \item
    RMSE measures the square root of the average squared difference
    between the forecasted and actual values.
  \item
    An RMSE of approximately 11 suggests that the forecasted values
    deviate from the actual values by an average of approximately 11
    units.
  \item
    This indicates a moderate level of error in the forecast.
  \end{itemize}
\item
  Mean Absolute Error (MAE)**: 7.96

  \begin{itemize}
  \item
    MAE measures the average absolute difference between the forecasted
    and actual values. I
  \item
    A MAE of approximately 9 indicates that, on average, the forecasted
    values deviate from the actual values by about 8 units of methane
    concentration.
  \end{itemize}
\item
  Mean Error (ME) **: 7.95

  \begin{itemize}
  \tightlist
  \item
    A ME of approximately 8 represents the average forecast error (which
    is close to the MAE.) It indicates a tendency for the forecast to be
    slightly higher (overestimation) on average.
  \end{itemize}
\end{itemize}

Discussing the accuracy and potential bias:

\begin{itemize}
\tightlist
\item
  In summary, while the forecast is reasonably accurate, there is a
  tendency for it to overestimate values!
\end{itemize}

\hypertarget{compute-and-compare-distribution-accuracy-measures-between-the-forecasted-and-actual-values}{%
\subsubsection{Compute and compare distribution accuracy measures
between the forecasted and actual
values}\label{compute-and-compare-distribution-accuracy-measures-between-the-forecasted-and-actual-values}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#mean and variance can let us compare the distributions of the actual and forecasted values}

\CommentTok{\# Calculate mean and variance for each dataset}
\NormalTok{mean\_april\_forecast }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(april\_forecast}\SpecialCharTok{$}\NormalTok{.mean)}
\NormalTok{variance\_april\_forecast }\OtherTok{\textless{}{-}} \FunctionTok{var}\NormalTok{(april\_forecast}\SpecialCharTok{$}\NormalTok{.mean)}

\NormalTok{mean\_actual\_methane }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(actual\_methane}\SpecialCharTok{$}\NormalTok{average)}
\NormalTok{variance\_actual\_methane }\OtherTok{\textless{}{-}} \FunctionTok{var}\NormalTok{(actual\_methane}\SpecialCharTok{$}\NormalTok{average)}

\CommentTok{\# Print mean and variance for each dataset}
\FunctionTok{cat}\NormalTok{(}\StringTok{"Mean of April Forecast:"}\NormalTok{, mean\_april\_forecast, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Mean of April Forecast: 1867.326
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"Mean of Actual Methane:"}\NormalTok{, mean\_actual\_methane, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Mean of Actual Methane: 1875.272
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"Variance of April Forecast:"}\NormalTok{, variance\_april\_forecast, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Variance of April Forecast: 125.1957
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"Variance of Actual Methane:"}\NormalTok{, variance\_actual\_methane, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Variance of Actual Methane: 340.8053
\end{verbatim}

The means are very similar, however the variances are very different
from eachother.

\hypertarget{estimate-the-best-fit-model-and-compare-with-the-etsaan-model}{%
\paragraph{Estimate the best fit model and compare with the ETS(A,A,N)
model}\label{estimate-the-best-fit-model-and-compare-with-the-etsaan-model}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# the "model" lets us run multiple models at a time; this will help us choose the best one in a second!}
\NormalTok{models\_to\_choose }\OtherTok{\textless{}{-}}\NormalTok{ prediction\_methane }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{model}\NormalTok{(}\AttributeTok{best =} \FunctionTok{ETS}\NormalTok{(average),}
        \AttributeTok{AAN =} \FunctionTok{ETS}\NormalTok{(average }\SpecialCharTok{\textasciitilde{}} \FunctionTok{error}\NormalTok{(}\StringTok{"A"}\NormalTok{) }\SpecialCharTok{+} \FunctionTok{trend}\NormalTok{(}\StringTok{"A"}\NormalTok{) }\SpecialCharTok{+} \FunctionTok{season}\NormalTok{(}\StringTok{"N"}\NormalTok{))) }
\end{Highlighting}
\end{Shaded}

\hypertarget{compute-forecasts-for-both-models}{%
\paragraph{Compute forecasts for both
models}\label{compute-forecasts-for-both-models}}

\begin{Shaded}
\begin{Highlighting}[]
\DocumentationTok{\#\# this will forecast for all of our different models}
\NormalTok{forecasting\_options }\OtherTok{\textless{}{-}}\NormalTok{ models\_to\_choose }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{forecast}\NormalTok{(}\AttributeTok{h=}\FunctionTok{nrow}\NormalTok{(actual\_methane))}


\DocumentationTok{\#\# this will run accuracy measures for each of our forecasted models }
\NormalTok{forecasting\_options }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{accuracy}\NormalTok{(}\AttributeTok{data =}\NormalTok{ actual\_methane) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{forecasting\_options =} \FunctionTok{c}\NormalTok{(}\StringTok{"best"}\NormalTok{, }\StringTok{"AAN"}\NormalTok{)) }\SpecialCharTok{\%\textgreater{}\%} \DocumentationTok{\#\# labeling like this bc this is the order that we listed them as arguments for model()}
  \FunctionTok{select}\NormalTok{(forecasting\_options, RMSE, MAE, ME)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 2 x 4
##   forecasting_options  RMSE   MAE    ME
##   <chr>               <dbl> <dbl> <dbl>
## 1 best                 22.5 19.8  19.8 
## 2 AAN                  11.2  7.97  7.95
\end{verbatim}

\hypertarget{compute-winkler_score-and-crps}{%
\paragraph{\texorpdfstring{Compute \texttt{winkler\_score} and
\texttt{CRPS}}{Compute winkler\_score and CRPS}}\label{compute-winkler_score-and-crps}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{forecasting\_options }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{accuracy}\NormalTok{(}\AttributeTok{data =}\NormalTok{ actual\_methane, }\FunctionTok{list}\NormalTok{(}\AttributeTok{winkler =}\NormalTok{winkler\_score, }\AttributeTok{crps=}\NormalTok{ CRPS)) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{forecasting\_options =} \FunctionTok{c}\NormalTok{(}\StringTok{"best"}\NormalTok{, }\StringTok{"AAN"}\NormalTok{)) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{select}\NormalTok{(forecasting\_options, winkler, crps)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
# A tibble: 2 x 3
  forecasting_options winkler  crps
  <chr>                 <dbl> <dbl>
1 best                   73.5 12.9 
2 AAN                    40.3  5.22
\end{verbatim}

\begin{itemize}
\item
  Winkler Score:

  \begin{itemize}
  \item
    Another accuracy measure. Lower Winkler Scores indicate better
    performance.
  \item
    The ``AAN'' model has a lower Winkler Score (40.30002) compared to
    the ``best'' model (73.51610), suggesting better accuracy in the
    ``AAN'' model.
  \end{itemize}
\item
  CRPS (Continuous Ranked Probability Score):

  \begin{itemize}
  \item
    Measures the accuracy of probabilistic forecasts. Lower CRPS values
    indicate better performance.
  \item
    The ``AAN'' model has a lower CRPS (5.216007) compared to the
    ``best'' model (12.870894), indicating better accuracy in terms of
    probabilistic forecasts.
  \end{itemize}
\end{itemize}

\hypertarget{discuss-which-model-had-the-better-forecast-and-whether-the-additive-seasonal-component-was-necessary}{%
\paragraph{Discuss which model had the better forecast and whether the
additive seasonal component was
necessary}\label{discuss-which-model-had-the-better-forecast-and-whether-the-additive-seasonal-component-was-necessary}}

In summary, the ``AAN'' model outperforms the ``best'' model in terms of
forecast accuracy. The ``AAN'' model has lower RMSE, MAE, ME, Winkler
Score, and CRPS, indicating better point and probabilistic forecast
accuracy.

Regarding the additive seasonal component, it appears that the ``AAN''
model, which includes the additive seasonal component, performed better.

\end{document}
